version: '3.4'

services:
  #HR Workflow
  hr_wf_api:
    image: hrwfapi
    build:
      context: .
      dockerfile: HR_WorkFlow_API/Dockerfile
    restart: always
    ports:
      - "7000:80"
    environment:
      - "ConnectionString:Host=wfpostgres;Database=hrdb;Username=postgres;Password=postgres;Port=5433"
    depends_on:
      - wfmongo
    networks:
      - dev

  #wfmongo
  wfmongo:
    image: "mongo:4.2.3"
    container_name: 'wfmongo'
    restart: always 
    ports:
      - 27017:27017
    environment: 
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    networks:
      - dev

  #wfpostgres
  # wfpostgres:
    # container_name: wfpostgres
    # image: postgres:latest
    # environment:
      # POSTGRES_DB: "hrdb"
      # POSTGRES_USER: "postgres"
      # POSTGRES_PASSWORD: "postgres"
    # ports:
      # - "55433:5433"
    # restart: always
    # networks:
     # - dev
    # command: -p 5433
  